- hosts: development
  vars:
  - myvar: "Vimal"
  tasks:
  - dnf: "name=httpd state=present"
  - copy: "content='hi LW {{ myvar }} finally end to end automated ....' dest=/var/www/html/index.html"
  - service: "name=httpd state=started"
    
